FROM python:3.11


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/

# Critical fix: prevent pip 24+ from removing setuptools
RUN pip install --no-cache-dir "pip<24" \
    && pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "finance_project.wsgi:application"]



