name: Backend-Deploy

on:
  push:
    branches: [ "ci-cd-setup" ]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: snapshot-backend
  ECS_CLUSTER: snapshot-cluster
  ECS_SERVICE: snapshot-backend-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set image tag
      id: vars
      run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

    - name: Build backend image
      run: |
        docker build -t $ECR_REPOSITORY:${{ steps.vars.outputs.TAG }} .

    - name: Tag backend image
      run: |
        ECR_URI=${{ steps.login-ecr.outputs.registry }}
        docker tag $ECR_REPOSITORY:${{ steps.vars.outputs.TAG }} $ECR_URI/$ECR_REPOSITORY:${{ steps.vars.outputs.TAG }}
        echo "BACKEND_URI=$ECR_URI/$ECR_REPOSITORY:${{ steps.vars.outputs.TAG }}" >> $GITHUB_ENV

    - name: Push backend image
      run: |
        docker push $BACKEND_URI

    - name: Update task definition image
      run: |
        sed -i "s|REPLACE_ME|${BACKEND_URI}|g" ecs-task-def-backend.json

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ecs-task-def-backend.json
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
